### ISSUE TITLE
Key Error While Reranking with det_cons

### ISSUE THREAD

**Issue by Hamedloghmani** [fani-lab/Adila#65]
Summary:
While running the `det_cons` algorithm on `random` baseline, I received a Key Error. After tracing back, we figured out in the `self.data` dictionary (reranking -> algs.py -> line 232) the index of popular users exceeds their size and we get key error.
We believe this is due to the  popular/non-popular ratio that we pass to the reranker (Popular: 0.43999999999999995, Non-popular: 0.56). Other ratios or other values of `k_max` might bypass this error if the required number of experts per each group does not exceed their availability.

**Run Settings:**
`prediction file` that caused the issue: `title.basics.tsv.filtered.mt75.ts3/random/t32059.s23.m2011.b4096/f0.test.pred`

`re-ranking algorithm`: det_cons

`k_max`: size of the team (2011 experts)

`ratio`: {True: 0.43999999999999995, False: 0.56}

`splits`: `title.basics.tsv.filtered.mt75.ts3/splits.json`

`teamsvec file` : `title.basics.tsv.filtered.mt75.ts3/teamsvecs.pkl`

**Traceback:**
```shell
Traceback (most recent call last):
  File "C:/Users/Hamed/AppData/Local/JetBrains/Toolbox/apps/PyCharm-P/ch-0/222.3739.56/plugins/python/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\Hamed\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\222.3739.56\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Projects/Equality/src/main.py", line 348, in <module>
    utility_metrics=args.utility_metrics)
  File "C:/Projects/Equality/src/main.py", line 242, in run
    reranked_idx, probs, elapsed_time = Reranking.rerank(preds, labels, new_output, ratios, algorithm, k_max, cutoff)
  File "C:/Projects/Equality/src/main.py", line 102, in rerank
    algorithm=algorithm)
  File "C:\Projects\Equality\env\lib\site-packages\reranking\__init__.py", line 18, in rerank
    return rerank(k_max, algorithm, verbose)
  File "C:\Projects\Equality\env\lib\site-packages\reranking\algs.py", line 80, in __call__
    return self.rerank_greedy(k_max_, algorithm, verbose)
  File "C:\Projects\Equality\env\lib\site-packages\reranking\algs.py", line 232, in rerank_greedy
    re_ranked_ranking.append(self.data[(next_attr, counts[next_attr])])
KeyError: (0, 856)
```

**Comment by hosseinfani** [comment]
@Hamedloghmani 
is this resolved? If so, pls close it.

**Comment by Hamedloghmani** [comment]
@hosseinfani 
After our pair-programming debug session, we figured this is a bug in the _reranking_ core library not in our code. 
With that being said, should I close the issue or keep it open?
Thank you
